title: Mythreyi Ramesh
email: mytibala@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "myra-7.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: epicreyi
github_username:  MyRa-7

header_pages:
  - about.md

show_excerpts: true
future: true
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

#markdown: redcarpet
extensions: [fenced_code_blocks]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html
